namespace TownOfUsMiraJK.Enums
{
    public enum TownOfUsJKRpc
    {
        GiveBread = 300,
        TriggerFamine,
        PassiveStarve,
        Starve,
        WrongStake,
        CorrectStake,
        SetUpProphet,
        TeleportBodyguard,
        GunslingerShot,
        TriggerWar,
        CollectSoul,
        TriggerDeath,
        ChangeDuel,
        DoDuel,
        TriggerBloodhound,
        WitchControl,
        WitchFeedback,
        SoulSwap,
        NecromancerReanimate,
        SniperShoot,
        GodfatherRecruit,
        SetDemagogueImmunity,
        DemagogueImmunitized,
        DemagogueHint,
        SecretaryStore,
        SecretaryVote,
        AddManhunterTarget,
        ManhunterWin,
        SanctifierSanctify,
    }
}
